### ISSUE TITLE
Data URL updated

### ISSUE THREAD

**Issue by Muhammad-Zeerak-Khan** [c17hawke/MLflow-CNN-app-FSDS#1]
NEW URL ="https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"

Kindly update the config.yaml file. 
Thankyou.

**Comment by c17hawke** [comment]
Thanks, @Muhammad-Zeerak-Khan, the link is updated now!
